server:
  port: 5000
spring:
  application:
    name: open-hack
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://HOSTNAME/DBNAME?serverTimezone=America/Los_Angeles
#    username: USERNAME
#    password: PASSWORD
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cmpe275?serverTimezone=America/Los_Angeles
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

