server:
  port: 8080
spring:
  application:
    name: open-hack
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://mysql-rds.ccgxyrruqnma.us-east-1.rds.amazonaws.com/cmpe275?serverTimezone=America/Los_Angeles
#    username: admin
#    password: OpenHack#2019
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/cmpe275?serverTimezone=America/Los_Angeles
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
  flyway:
    schemas: ["cmpe275"]
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
